name: "Mattermost Notify"
inputs:
  webhook:
    description: Mattermost webhook
    required: true
  channel:
    description: Channel path name
    required: false
    default: ""
  username:
    description: Username
    required: false
    default: ""
  iconEmoji:
    description: Icon emoji
    required: false
    default: ":tractor:"
runs:
  using: composite
  steps:
    - name: Get last commit SHA
      id: last_commit
      shell: bash
      run: |
        SHA_7=$(git rev-parse --short HEAD)
        git fetch origin master
        LAST_COMMIT=$(git rev-parse origin/master)
        echo "last_commit_sha=$LAST_COMMIT" >> $GITHUB_OUTPUT
        echo "sha_7=$SHA_7" >> $GITHUB_OUTPUT
        echo "Last commit SHA: $LAST_COMMIT"
        echo "Current commit SHA: ${{ github.sha }}"
    - name: Get current PR
      uses: 8BitJonny/gh-get-current-pr@3.0.0
      id: PR
    - name: Deployment Notification
      if: ${{ github.sha == steps.last_commit.outputs.last_commit_sha }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_USERNAME: ${{ inputs.username }}
        SLACK_ICON_EMOJI: ${{ inputs.iconEmoji }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_COLOR: ${{ job.status }}
        SLACK_LINK_NAMES: true
        SLACK_FOOTER: ${{ steps.last_commit.outputs.sha_7 }}
        MSG_MINIMAL: true
        SLACK_TITLE: ${{ github.repository }}
        SLACK_MESSAGE: >
          **[${{ steps.PR.outputs.pr_title }}](${{ github.server_url }}/${{ github.repository }}/pull/${{ steps.PR.outputs.number }})**

          ${{ steps.PR.outputs.pr_body }}
    - name: Deployment Rollback Notification
      if: ${{ github.sha != steps.last_commit.outputs.last_commit_sha }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ inputs.channel }}
        SLACK_USERNAME: ${{ inputs.username }}
        SLACK_ICON_EMOJI: ${{ inputs.iconEmoji }}
        SLACK_WEBHOOK: ${{ inputs.webhook }}
        SLACK_COLOR: "#ffcc00"
        SLACK_LINK_NAMES: true
        SLACK_FOOTER: ${{ steps.last_commit.outputs.sha_7 }}
        MSG_MINIMAL: true
        SLACK_TITLE: ${{ github.repository }}
        SLACK_MESSAGE: >
          :rewind: Rolled back to [${{ steps.last_commit.outputs.sha_7 }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
