name: PR
on:
  pull_request:
    branches: ["*"]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: valitydev/action-mattermost-notify@v0.1.4
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: "frontend-deployments"
          username: "Demo"
