name: "Frontend: Notify"
on:
  push:
    branches: ['master', 'main']
  pull_request:
    branches: ['*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Mattermost Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: "frontend-deployments"
          SLACK_USERNAME: "Frontend"
          SLACK_ICON_EMOJI: ":tractor:"
          SLACK_WEBHOOK: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_LINK_NAMES: true
          SLACK_FOOTER: ""
          MSG_MINIMAL: true
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: |
            **[${{ github.event.pull_request.title }}](${{ github.server_url }}/${{ github.repository }}|
            /pull/${{ github.event.number }})**

            ${{ github.event.pull_request.body }}
