name: Notify
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get commits SHA
        id: commits_sha
        shell: bash
        run: |
          LAST_COMMIT=$(git rev-parse origin/master)
          echo "Last commit SHA: $LAST_COMMIT"
          echo "::set-output name=last_commit_sha::$LAST_COMMIT"
          echo ${{ github.sha }}
      - name: Mattermost Notification
        uses: ./
        if: ${{ github.sha == steps.commits_sha.outputs.last_commit_sha }}
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: "frontend-deployments"
          username: "Frontend"
