name: Notify
on:
  push:
    branches: ["master", "main"]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get commits SHA
        id: commits_sha
        run: |
          LAST_COMMIT=$(git log -n 1 --pretty=format:%H)
          echo "Last commit SHA: $LAST_COMMIT"
          echo "::set-output name=last_commit_sha::$LAST_COMMIT"
          CURRENT_COMMIT=$(git rev-parse HEAD)
          echo "Current commit SHA: $CURRENT_COMMIT"
          echo "::set-output name=current_commit_sha::$CURRENT_COMMIT"
          echo ${{ github.sha }}
      - name: Mattermost Notification
        uses: ../../action
        if: ${{ steps.commits_sha.outputs.last_commit_sha == steps.commits_sha.outputs.current_commit_sha }}
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: "frontend-deployments"
          username: "Frontend"
