name: Notify
on:
  push:
    branches: ["master", "main"]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Mattermost Notification
        uses: ./
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: "frontend-deployments"
          username: "Frontend"
