name: Notify
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get last commit SHA
        id: last_commit
        shell: bash
        run: |
          LAST_COMMIT=$(git rev-parse master)
          echo "last_commit_sha=$LAST_COMMIT" >> $GITHUB_OUTPUT
          echo "Last commit SHA: $LAST_COMMIT"
          echo "2: $(git rev-parse HEAD)"
      - name: Mattermost Notification
        uses: ./
        if: ${{ github.sha == steps.last_commit.outputs.last_commit_sha }}
        with:
          webhook: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
          channel: "frontend-deployments"
          username: "Frontend"
